services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    networks:
      - internal